name: Validate Terraform, Run Tests, and Create Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  run-tests:
    runs-on: ubuntu-latest
    needs: terraform-validate  # Garante que os testes rodem apenas após a validação do Terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install test dependencies
        run: |
          pip install -r tests/requirements.txt
          pip install coverage coverage-badge

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s tests
          coverage report -m --fail-under=90
          coverage html
          coverage-badge -o coverage.svg -f

      - name: List files in tests directory before moving
        run: |
          echo "Listing files in tests directory"
          ls -R tests  # Lista todos os arquivos dentro do diretório tests

      - name: Move coverage files to reports directory
        run: |
          mv htmlcov tests/reports/htmlcov
          mv coverage.svg tests/reports/coverage.svg

      - name: List files in test reports directory
        run: |
          echo "Listing files in tests/reports directory after move"
          ls -R tests/reports  # Lista todos os arquivos dentro de tests/reports

      # Upload do relatório de cobertura
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: tests/reports/htmlcov

      # Upload do badge de cobertura
      - name: Upload coverage badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: tests/reports/coverage.svg

  sync-develop-to-main:
    runs-on: ubuntu-latest
    needs: run-tests  # Só cria o PR se os testes passarem
    if: success()  # Executa apenas se os jobs anteriores forem bem-sucedidos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch and Checkout Branches
        run: |
          git fetch origin
          git checkout develop
          git pull origin develop
          git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}

      - name: Merge PR to Develop
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin develop
        env:
          token: ${{ secrets.PAT }}

      - name: Create or Update Pull Request to Main
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: existingPullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'develop',
              base: 'main',
              state: 'open'
            });

            if (existingPullRequests.length > 0) {
              const pullRequest = existingPullRequests[0];
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequest.number,
                title: 'Sync develop to main',
                body: 'This is an automated PR to sync changes from develop to main.'
              });
              console.log(`Updated pull request: ${pullRequest.html_url}`);
            } else {
              const { data: pullRequest } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Sync develop to main',
                head: 'develop',
                base: 'main',
                body: 'This is an automated PR to sync changes from develop to main.',
                draft: false
              });
              console.log(`Created pull request: ${pullRequest.html_url}`);
            }