name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Passo para empacotar a Lambda com dependências
      - name: Create ZIP file for sendemail Lambda
        run: |
          mkdir -p lambda/sendemail
          cp -r ./src/sendemail/* lambda/sendemail/
          cd lambda/sendemail
          
          # Instalar dependências diretamente no diretório
          pip install -r ../../src/sendemail/requirements.txt -t .
          
          # Criar o arquivo ZIP
          zip -r sendemail_lambda_function.zip .
          cd ../../

      # Verificar se o arquivo ZIP foi criado
      - name: Check if ZIP files exist
        run: |
          if [ ! -f lambda/sendemail/sendemail_lambda_function.zip ]; then
            echo "sendemail Lambda ZIP file not found!"
            exit 1
          fi

      # Listar os arquivos no ZIP
      - name: List files in ZIP
        run: unzip -l lambda/sendemail/sendemail_lambda_function.zip

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Terraform Refresh
      - name: Terraform Refresh
        run: terraform refresh -input=false
        working-directory: ./infra

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra